# 02 — Baseline RAG

**VerifiedRAG — Multi-Agent RAG with Claim-Level Fact Verification**

This notebook implements the standard RAG baseline that later verified/agentic systems will be compared against.

```text
Question → Query Embedding → FAISS → Top-k Evidence → Prompt → Local LLM → Answer + Citations
```

The corpus and FAISS index are loaded from `01_data_preparation.ipynb`, keeping the retrieval conditions fixed for fair experiments.

## 1. Install dependencies

Designed for Google Colab. A GPU is strongly recommended for local LLM generation.

In [1]:
!pip -q install transformers accelerate bitsandbytes sentence-transformers faiss-cpu pandas numpy tqdm

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.0/41.0 MB 19.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.8/18.8 MB 65.6 MB/s eta 0:00:00

In [2]:
# 1. Clone your repository to get the project files
!git clone https://github.com/faizzanasghar/Verified-RAG.git /content/Verified-RAG

# 2. Run the data preparation notebook in this runtime to build the data and FAISS index
%run /content/Verified-RAG/notebooks/01_data_preparation.ipynb

Cloning into '/content/Verified-RAG'...
remote: Enumerating objects: 26, done.
remote: Counting objects: 100% (26/26), done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 26 (delta 3), reused 24 (delta 2), pack-reused 0 (from 0)
Receiving objects: 100% (26/26), 897.76 KiB | 5.95 MiB/s, done.
Resolving deltas: 100% (3/3), done.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25.8/25.8 MB 54.8 MB/s eta 0:00:00
warning: The `fitz` API is deprecated and will be removed in future. Use `import pymupdf` instead.
PyTorch: 2.11.0+cu128
CUDA available: True
GPU: Tesla T4
Project root: /content/Verified-RAG
Raw PDFs: /content/Verified-RAG/data/raw_pdfs
Processed data: /content/Verified-RAG/data/processed
Vector store: /content/Verified-RAG/data/vector_store

,paper_id,title,path,status,size_bytes
0,attention_2017,Attention Is All You Need,/content/Verified-RAG/data/raw_pdfs/attention_...,downloaded,2215244
1,resnet_2015,Deep Residual Learning for Image Recognition,/content/Verified-RAG/data/raw_pdfs/resnet_201...,downloaded,819383
2,bert_2018,BERT: Pre-training of Deep Bidirectional Trans...,/content/Verified-RAG/data/raw_pdfs/bert_2018.pdf,downloaded,775166
3,adam_2014,Adam: A Method for Stochastic Optimization,/content/Verified-RAG/data/raw_pdfs/adam_2014.pdf,downloaded,584641
4,gpt2_2019,Language Models are Unsupervised Multitask Lea...,/content/Verified-RAG/data/raw_pdfs/gpt2_2019.pdf,downloaded,582775

adam_2014.pdf                                 570.9 KB
attention_2017.pdf                            2163.3 KB
bert_2018.pdf                                 757.0 KB
gpt2_2019.pdf                                 569.1 KB
resnet_2015.pdf                               800.2 KB

Extracting PDFs:   0%|          | 0/5 [00:00<?, ?it/s]

Extracted pages: 82

         paper_id                                              title  pages
0       adam_2014         Adam: A Method for Stochastic Optimization     15
1  attention_2017                          Attention Is All You Need     15
2       bert_2018  BERT: Pre-training of Deep Bidirectional Trans...     16
3       gpt2_2019  Language Models are Unsupervised Multitask Lea...     24
4     resnet_2015       Deep Residual Learning for Image Recognition     12

Sample page:
Published as a conference paper at ICLR 2015
ADAM: A METHOD FOR STOCHASTIC OPTIMIZATION
Diederik P. Kingma*
University of Amsterdam, OpenAI
dpkingma@openai.com
Jimmy Lei Ba∗
University of Toronto
jimmy@psi.utoronto.ca
ABSTRACT
We introduce Adam, an algorithm for ﬁrst-order gradient-based optimization of
stochastic objective functions, based on adaptive estimates of lower-order mo-
ments. The method is straightforward to implement, is computationally efﬁcient,
has little memory requirements, is invariant to diagonal rescaling of the gradients,
and is well suited for problems that are large in terms of data and/or parameters.
The method is also appropriate for non-stationary objectives and problems with
very noisy and/or sparse gradients. The hyper-parameters have intuitive interpre-
tations and typically require little tuning. Some connections to related algorithms,
on which Adam was inspired, are discussed. We also analyze the theoretical con-
vergence properties of the algorithm and provide a regret bound on the conver-
gence rate that is comparable to the best known results under the online convex
optimization framework. Empirical results demonstrate that Adam works well in
practice and compares favorably to other stochastic optimization methods. Finally,
we discuss AdaMax, a variant of Adam based on the inﬁnity norm.
1
INTRODUCTION
Stochastic gradient-based optimization is of core practical importance in many ﬁelds of science and
engineering. Many problems in these ﬁelds can be cast as the optimization of some scalar parameter-
ized objective function requiring maximization or minimization with respect to its parameters. If the
function is differentiable w.r.t. its parameters, gradient descent is a relatively efﬁcient optimization
method, since the computation of ﬁrst-order partial derivatives w.r.t. all the parameters is of the same
computational complexity as just evaluating the function. Often, objective functions are stochastic.
For example, many objective fu
Usable pages after cleaning: 82

Chunking pages:   0%|          | 0/82 [00:00<?, ?it/s]

Total chunks: 516
Before deduplication: 516
After deduplication:  516
Removed:              0
Example chunk metadata:
{
  "paper_id": "adam_2014",
  "title": "Adam: A Method for Stochastic Optimization",
  "page": 1,
  "chunk_on_page": 0,
  "text": "Published as a conference paper at ICLR 2015 ADAM: A METHOD FOR STOCHASTIC OPTIMIZATION Diederik P. Kingma* University of Amsterdam, OpenAI dpkingma@openai.com Jimmy Lei Ba∗ University of Toronto jimmy@psi.utoronto.ca ABSTRACT We introduce Adam, an algorithm for ﬁrst-order gradient-based optimization of stochastic objective functions, based on adaptive estimates of lower-order moments. The method is straightforward to implement, is computationally efﬁcient, has little memory requirements, is invariant to diagonal rescaling of the gradients, and is well suited for problems that are large in terms of data and/or parameters. The method is also appropriate for non-stationary objectives and problems with very noisy and/or sparse gradients. The hyper-parameters have intuitive interpretations and typically require little tuning. Some connections to related algorithms, on which Adam was inspired, are discussed",
  "text_hash": "f9a9f0b4cbb5042b7776594d87234066de9a0929c767d7cd81c0c513c7d817a1",
  "chunk_index": 0,
  "chunk_id": "adam_2014_p001_c000"
}
Number of chunks: 516
Minimum length:  55
Mean length:     700.12
Median length:   822.5
Maximum length:  1000

,paper_id,title,chunks,avg_chars,min_chars,max_chars
0,adam_2014,Adam: A Method for Stochastic Optimization,70,714.3,216,999
1,attention_2017,Attention Is All You Need,68,695.9,204,998
2,bert_2018,BERT: Pre-training of Deep Bidirectional Trans...,106,722.4,190,1000
3,gpt2_2019,Language Models are Unsupervised Multitask Lea...,166,692.2,156,1000
4,resnet_2015,Deep Residual Learning for Image Recognition,106,683.5,55,1000

Saved:
/content/Verified-RAG/data/processed/chunks.jsonl
/content/Verified-RAG/data/processed/papers.json
/content/Verified-RAG/data/processed/corpus_metadata.json

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Model: sentence-transformers/all-MiniLM-L6-v2
Device: cuda
Embedding dimension: 384

/tmp/ipykernel_4077/335280999.py:12: FutureWarning: The `get_sentence_embedding_dimension` method has been renamed to `get_embedding_dimension`.
  print("Embedding dimension:", embedding_model.get_sentence_embedding_dimension())

Batches:   0%|          | 0/9 [00:00<?, ?it/s]

Embedding matrix shape: (516, 384)
FAISS index type: IndexFlatIP
Vectors in index: 516
Vector dimension: 384
Saved:
/content/Verified-RAG/data/vector_store/faiss.index
/content/Verified-RAG/data/vector_store/chunks_metadata.json
/content/Verified-RAG/data/vector_store/index_metadata.json
==========================================================================================
Rank: 1
Score: 0.6450
Paper: Deep Residual Learning for Image Recognition
Page: 1
Chunk ID: resnet_2015_p001_c000
Deep Residual Learning for Image Recognition Kaiming He Xiangyu Zhang Shaoqing Ren Jian Sun Microsoft Research {kahe, v-xiangz, v-shren, jiansun}@microsoft.com Abstract Deeper neural networks are more difﬁcult to train. We present a residual learning framework to ease the training of networks that are substantially deeper than those used previously. We explicitly reformulate the layers as learning residual functions with reference to the layer inputs, instead of learning unreferenced functions. We provide comprehensive empirical evidence showing that these residual networks are easier to optimize, and can gain accuracy from considerably increased depth. On the ImageNet dataset we evaluate residual nets with a depth of up to 152 layers—8× deeper than VGG nets [41] but still having lower complexity. An ensemble of these residual nets achieves 3.57% error on the ImageNet test set. This result won the 1st place on the ILSVRC 2015 classiﬁcation task
==========================================================================================
Rank: 2
Score: 0.6362
Paper: Deep Residual Learning for Image Recognition
Page: 5
Chunk ID: resnet_2015_p005_c003
curacy (Table 3), suggesting that the solver works to some extent. We conjecture that the deep plain nets may have exponentially low convergence rates which impact the reducing of the training error3. The reason for such optimization difﬁculties will be studied in the future. Residual Networks. Next we evaluate 18-layer and 34layer residual nets (ResNets)
==========================================================================================
Rank: 3
Score: 0.6107
Paper: Deep Residual Learning for Image Recognition
Page: 2
Chunk ID: resnet_2015_p002_c000
identity weight layer weight layer relu relu F(x)+x x F(x) x Figure 2. Residual learning: a building block. are comparably good or better than the constructed solution (or unable to do so in feasible time). In this paper, we address the degradation problem by introducing a deep residual learning framework. Instead of hoping each few stacked layers directly ﬁt a desired underlying mapping, we explicitly let these layers ﬁt a residual mapping. Formally, denoting the desired underlying mapping as H(x), we let the stacked nonlinear layers ﬁt another mapping of F(x) := H(x)−x. The original mapping is recast into F(x)+x. We hypothesize that it is easier to optimize the residual mapping than to optimize the original, unreferenced mapping. To the extreme, if an identity mapping were optimal, it would be easier to push the residual to zero than to ﬁt an identity mapping by a stack of nonlinear layers
==========================================================================================
Rank: 4
Score: 0.6077
Paper: Deep Residual Learning for Image Recognition
Page: 2
Chunk ID: resnet_2015_p002_c008
(approaching zero), the layers in highway networks represent non-residual functions. On the contrary, our formulation always learns residual functions our identity shortcuts are never closed, and all information is always passed through, with additional residual functions to be learned. In addition, high2
==========================================================================================
Rank: 5
Score: 0.5683
Paper: Deep Residual Learning for Image Recognition
Page: 2
Chunk ID: resnet_2015_p002_c002
We show that: 1) Our extremely deep residual nets are easy to optimize, but the counterpart “plain” nets (that simply stack layers) exhibit higher training error when the depth increases; 2) Our deep residual nets can easily enjoy accuracy gains from greatly increased depth, producing results substantially better than previous networks. Similar phenomena are also shown on the CIFAR-10 set [20], suggesting that the optimization difﬁculties and the effects of our method are not just akin to a particular dataset. We present successfully trained models on this dataset with over 100 layers, and explore models with over 1000 layers. On the ImageNet classiﬁcation dataset [36], we obtain excellent results by extremely deep residual nets. Our 152layer residual net is the deepest network ever presented on ImageNet, while still having lower complexity than VGG nets [41]. Our ensemble has 3.57% top-5 error on the ImageNet test set, and won the 1st place in the ILSVRC 2015 classiﬁcation competition
All integrity checks passed.
{
  "project": "VerifiedRAG",
  "stage": "01_data_preparation",
  "num_source_papers": 5,
  "num_extracted_pages": 82,
  "num_final_chunks": 516,
  "chunk_size_chars": 1000,
  "chunk_overlap_chars": 150,
  "embedding_model": "sentence-transformers/all-MiniLM-L6-v2",
  "embedding_dimension": 384,
  "faiss_index": "IndexFlatIP",
  "normalized_embeddings": true,
  "device_used_for_embeddings": "cuda"
}

Data preparation complete.
Saved notebook to /content/Verified-RAG/notebooks/01_data_preparation.ipynb

## 2. Imports and project paths

In [3]:
from pathlib import Path
import json
import re
import time
import pandas as pd
import torch
import faiss
from tqdm.auto import tqdm
from sentence_transformers import SentenceTransformer
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig

PROJECT_ROOT = Path("/content/Verified-RAG")
PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"
VECTOR_DIR = PROJECT_ROOT / "data" / "vector_store"
RESULTS_DIR = PROJECT_ROOT / "results"

RESULTS_DIR.mkdir(parents=True, exist_ok=True)

print("Project:", PROJECT_ROOT)

Project: /content/Verified-RAG

## 3. Check the Colab runtime

In [4]:
print("PyTorch:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
    print("VRAM:", round(torch.cuda.get_device_properties(0).total_memory / 1024**3, 2), "GB")
else:
    print("WARNING: No GPU detected. LLM inference may be very slow.")

PyTorch: 2.11.0+cu128
CUDA available: True
GPU: Tesla T4
VRAM: 14.56 GB

## 4. Load the corpus and FAISS index

In [5]:
required = [
    PROCESSED_DIR / "chunks.jsonl",
    PROCESSED_DIR / "papers.json",
    PROCESSED_DIR / "corpus_metadata.json",
    VECTOR_DIR / "faiss.index",
    VECTOR_DIR / "chunks_metadata.json",
]
missing = [str(p) for p in required if not p.exists()]
if missing:
    raise FileNotFoundError("Run 01_data_preparation.ipynb first. Missing:\n" + "\n".join(missing))

with (PROCESSED_DIR / "corpus_metadata.json").open(encoding="utf-8") as f:
    corpus_metadata = json.load(f)
with (PROCESSED_DIR / "papers.json").open(encoding="utf-8") as f:
    papers = json.load(f)
with (VECTOR_DIR / "chunks_metadata.json").open(encoding="utf-8") as f:
    chunks_metadata = json.load(f)

faiss_index = faiss.read_index(str(VECTOR_DIR / "faiss.index"))

print("Papers:", len(papers))
print("Chunks:", len(chunks_metadata))
print("FAISS vectors:", faiss_index.ntotal)
print(json.dumps(corpus_metadata, indent=2))

Papers: 5
Chunks: 516
FAISS vectors: 516
{
  "num_papers": 5,
  "num_pages": 82,
  "num_chunks": 516,
  "chunk_size": 1000,
  "chunk_overlap": 150,
  "embedding_model": "sentence-transformers/all-MiniLM-L6-v2"
}

## 5. Load the same embedding model used during data preparation

In [6]:
EMBEDDING_MODEL_NAME = corpus_metadata.get(
    "embedding_model", "sentence-transformers/all-MiniLM-L6-v2"
)
embedding_device = "cuda" if torch.cuda.is_available() else "cpu"
embedding_model = SentenceTransformer(EMBEDDING_MODEL_NAME, device=embedding_device)

print("Embedding model:", EMBEDDING_MODEL_NAME)
print("Device:", embedding_device)
print("Dimension:", embedding_model.get_sentence_embedding_dimension())

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Embedding model: sentence-transformers/all-MiniLM-L6-v2
Device: cuda
Dimension: 384

/tmp/ipykernel_4077/4284008764.py:9: FutureWarning: The `get_sentence_embedding_dimension` method has been renamed to `get_embedding_dimension`.
  print("Dimension:", embedding_model.get_sentence_embedding_dimension())

## 6. Retriever

In [7]:
DEFAULT_TOP_K = 5

def retrieve(query: str, top_k: int = DEFAULT_TOP_K, min_score=None):
    query_embedding = embedding_model.encode(
        [query], convert_to_numpy=True, normalize_embeddings=True
    ).astype("float32")
    scores, indices = faiss_index.search(query_embedding, top_k)

    results = []
    for score, idx in zip(scores[0], indices[0]):
        if idx == -1:
            continue
        score = float(score)
        if min_score is not None and score < min_score:
            continue
        item = chunks_metadata[int(idx)].copy()
        item["score"] = score
        results.append(item)
    return results

def display_retrieval_results(results, max_chars=1000):
    for rank, item in enumerate(results, 1):
        print("=" * 100)
        print(f"Rank: {rank}")
        print(f"Score: {item['score']:.4f}")
        print(f"Paper: {item['title']}")
        print(f"Page: {item['page']}")
        print(f"Chunk: {item['chunk_id']}")
        print("-" * 100)
        print(item["text"][:max_chars])
        print()

test_results = retrieve(
    "What problem does residual learning solve in very deep neural networks?", 5
)
display_retrieval_results(test_results)

====================================================================================================
Rank: 1
Score: 0.6674
Paper: Deep Residual Learning for Image Recognition
Page: 1
Chunk: resnet_2015_p001_c000
----------------------------------------------------------------------------------------------------
Deep Residual Learning for Image Recognition Kaiming He Xiangyu Zhang Shaoqing Ren Jian Sun Microsoft Research {kahe, v-xiangz, v-shren, jiansun}@microsoft.com Abstract Deeper neural networks are more difﬁcult to train. We present a residual learning framework to ease the training of networks that are substantially deeper than those used previously. We explicitly reformulate the layers as learning residual functions with reference to the layer inputs, instead of learning unreferenced functions. We provide comprehensive empirical evidence showing that these residual networks are easier to optimize, and can gain accuracy from considerably increased depth. On the ImageNet dataset we evaluate residual nets with a depth of up to 152 layers—8× deeper than VGG nets [41] but still having lower complexity. An ensemble of these residual nets achieves 3.57% error on the ImageNet test set. This result won the 1st place on the ILSVRC 2015 classiﬁcation task

====================================================================================================
Rank: 2
Score: 0.6566
Paper: Deep Residual Learning for Image Recognition
Page: 5
Chunk: resnet_2015_p005_c003
----------------------------------------------------------------------------------------------------
curacy (Table 3), suggesting that the solver works to some extent. We conjecture that the deep plain nets may have exponentially low convergence rates which impact the reducing of the training error3. The reason for such optimization difﬁculties will be studied in the future. Residual Networks. Next we evaluate 18-layer and 34layer residual nets (ResNets)

====================================================================================================
Rank: 3
Score: 0.6066
Paper: Deep Residual Learning for Image Recognition
Page: 2
Chunk: resnet_2015_p002_c002
----------------------------------------------------------------------------------------------------
We show that: 1) Our extremely deep residual nets are easy to optimize, but the counterpart “plain” nets (that simply stack layers) exhibit higher training error when the depth increases; 2) Our deep residual nets can easily enjoy accuracy gains from greatly increased depth, producing results substantially better than previous networks. Similar phenomena are also shown on the CIFAR-10 set [20], suggesting that the optimization difﬁculties and the effects of our method are not just akin to a particular dataset. We present successfully trained models on this dataset with over 100 layers, and explore models with over 1000 layers. On the ImageNet classiﬁcation dataset [36], we obtain excellent results by extremely deep residual nets. Our 152layer residual net is the deepest network ever presented on ImageNet, while still having lower complexity than VGG nets [41]. Our ensemble has 3.57% top-5 error on the ImageNet test set, and won the 1st place in the ILSVRC 2015 classiﬁcation competition

====================================================================================================
Rank: 4
Score: 0.6024
Paper: Deep Residual Learning for Image Recognition
Page: 2
Chunk: resnet_2015_p002_c008
----------------------------------------------------------------------------------------------------
(approaching zero), the layers in highway networks represent non-residual functions. On the contrary, our formulation always learns residual functions our identity shortcuts are never closed, and all information is always passed through, with additional residual functions to be learned. In addition, high2

====================================================================================================
Rank: 5
Score: 0.6022
Paper: Deep Residual Learning for Image Recognition
Page: 2
Chunk: resnet_2015_p002_c000
----------------------------------------------------------------------------------------------------
identity weight layer weight layer relu relu F(x)+x x F(x) x Figure 2. Residual learning: a building block. are comparably good or better than the constructed solution (or unable to do so in feasible time). In this paper, we address the degradation problem by introducing a deep residual learning framework. Instead of hoping each few stacked layers directly ﬁt a desired underlying mapping, we explicitly let these layers ﬁt a residual mapping. Formally, denoting the desired underlying mapping as H(x), we let the stacked nonlinear layers ﬁt another mapping of F(x) := H(x)−x. The original mapping is recast into F(x)+x. We hypothesize that it is easier to optimize the residual mapping than to optimize the original, unreferenced mapping. To the extreme, if an identity mapping were optimal, it would be easier to push the residual to zero than to ﬁt an identity mapping by a stack of nonlinear layers

## 7. Load the local open-source LLM

Default model: `Qwen/Qwen2.5-3B-Instruct`. A 4-bit load is used on CUDA to reduce VRAM usage.

In [8]:
MODEL_NAME = "Qwen/Qwen2.5-3B-Instruct"

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, trust_remote_code=True)

if torch.cuda.is_available():
    quantization_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=torch.float16,
        bnb_4bit_use_double_quant=True,
    )
    model = AutoModelForCausalLM.from_pretrained(
        MODEL_NAME,
        quantization_config=quantization_config,
        device_map="auto",
        torch_dtype=torch.float16,
        trust_remote_code=True,
    )
else:
    print("CPU fallback selected; inference can be slow.")
    model = AutoModelForCausalLM.from_pretrained(
        MODEL_NAME,
        device_map="auto",
        torch_dtype=torch.float32,
        trust_remote_code=True,
    )

model.eval()
print("Loaded:", MODEL_NAME)

config.json:   0%|          | 0.00/661 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/7.30k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

[transformers] `torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors.index.json:   0%|          | 0.00/35.6k [00:00<?, ?B/s]

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/434 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

Loaded: Qwen/Qwen2.5-3B-Instruct

## 8. Build the RAG prompt

In [9]:
SYSTEM_PROMPT = """You are a technical question-answering assistant.

Answer the user's question using ONLY the supplied source context.

Rules:
1. Do not invent facts that are not supported by the context.
2. If the context is insufficient, say so.
3. Every substantive factual claim should include a source citation.
4. Citations must use exactly: [SOURCE: chunk_id]
5. Do not create or modify source IDs.
6. Be concise and technically precise.
"""

def build_context(results):
    blocks = []
    for item in results:
        blocks.append(
            f"[SOURCE: {item['chunk_id']}]\n"
            f"Paper: {item['title']}\n"
            f"Page: {item['page']}\n"
            f"Text:\n{item['text']}"
        )
    return "\n\n".join(blocks)

def build_rag_prompt(question, results):
    return f"""Answer the following question using only the source context.

QUESTION:
{question}

SOURCE CONTEXT:
{build_context(results)}

Remember:
- Every substantive factual claim must have a [SOURCE: chunk_id] citation.
- If the context is insufficient, explicitly state that.
- Do not use information that is not supported by the supplied context.
"""

## 9. LLM generation

In [10]:
def generate_answer(question, retrieved_results, max_new_tokens=350):
    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": build_rag_prompt(question, retrieved_results)},
    ]
    prompt_text = tokenizer.apply_chat_template(
        messages, tokenize=False, add_generation_prompt=True
    )
    inputs = tokenizer(
        prompt_text, return_tensors="pt", truncation=True, max_length=8192
    )
    if torch.cuda.is_available():
        inputs = {k: v.to(model.device) for k, v in inputs.items()}

    start = time.perf_counter()
    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            pad_token_id=tokenizer.eos_token_id,
        )
    elapsed = time.perf_counter() - start

    input_len = inputs["input_ids"].shape[1]
    generated = outputs[0][input_len:]
    answer = tokenizer.decode(generated, skip_special_tokens=True).strip()

    return {
        "answer": answer,
        "generation_time_seconds": elapsed,
        "prompt_tokens": int(input_len),
        "generated_tokens": int(len(generated)),
    }

## 10. Complete baseline RAG pipeline

In [11]:
def baseline_rag(question, top_k=5, min_score=None, max_new_tokens=350):
    retrieval_start = time.perf_counter()
    retrieved = retrieve(question, top_k=top_k, min_score=min_score)
    retrieval_time = time.perf_counter() - retrieval_start

    if not retrieved:
        return {
            "question": question,
            "answer": "I could not retrieve sufficiently relevant evidence.",
            "sources": [],
            "retrieved_chunks": [],
            "retrieval_time_seconds": retrieval_time,
            "generation_time_seconds": 0.0,
            "prompt_tokens": 0,
            "generated_tokens": 0,
        }

    generation = generate_answer(question, retrieved, max_new_tokens)

    return {
        "question": question,
        "answer": generation["answer"],
        "sources": [
            {
                "chunk_id": r["chunk_id"],
                "paper_id": r["paper_id"],
                "title": r["title"],
                "page": r["page"],
                "score": r["score"],
            }
            for r in retrieved
        ],
        "retrieved_chunks": retrieved,
        "retrieval_time_seconds": retrieval_time,
        "generation_time_seconds": generation["generation_time_seconds"],
        "prompt_tokens": generation["prompt_tokens"],
        "generated_tokens": generation["generated_tokens"],
    }

## 11. Run one baseline RAG query

In [12]:
question = (
    "What is the main idea behind residual learning, "
    "and why does it help train very deep neural networks?"
)
result = baseline_rag(question, top_k=5, max_new_tokens=300)

print("QUESTION\n", result["question"])
print("\nANSWER\n", result["answer"])
print("\nSOURCES")
for source in result["sources"]:
    print(
        f"- {source['chunk_id']} | {source['title']} | "
        f"page {source['page']} | score={source['score']:.4f}"
    )
print("\nTIMING")
print("Retrieval:", round(result["retrieval_time_seconds"], 3), "s")
print("Generation:", round(result["generation_time_seconds"], 3), "s")

QUESTION
 What is the main idea behind residual learning, and why does it help train very deep neural networks?

ANSWER
 The main idea behind residual learning is to explicitly learn residual functions instead of unreferenced functions. This approach helps train very deep neural networks by making the optimization process easier. By casting the original function as \( F(x) + x \), the residual learning framework allows the network to focus on fitting the residual mapping rather than the original mapping directly. This makes the training process smoother and enables deeper networks to achieve better performance [SOURCE: resnet_2015_p001_c000].

Residual learning helps train very deep neural networks because it simplifies the optimization process. As networks become deeper, residual learning allows them to gain accuracy from increased depth, which is not possible with traditional methods [SOURCE: resnet_2015_p002_c002]. The framework shows that residual networks can be 8 times deeper than previous networks like VGG nets while maintaining lower complexity [SOURCE: resnet_2015_p001_c000].

SOURCES
- resnet_2015_p001_c000 | Deep Residual Learning for Image Recognition | page 1 | score=0.5869
- resnet_2015_p002_c008 | Deep Residual Learning for Image Recognition | page 2 | score=0.5266
- resnet_2015_p002_c002 | Deep Residual Learning for Image Recognition | page 2 | score=0.5109
- resnet_2015_p002_c000 | Deep Residual Learning for Image Recognition | page 2 | score=0.5065
- resnet_2015_p003_c000 | Deep Residual Learning for Image Recognition | page 3 | score=0.5005

TIMING
Retrieval: 0.057 s
Generation: 16.114 s

## 12. Citation diagnostics

In [13]:
SOURCE_PATTERN = re.compile(r"\[SOURCE:\s*([^\]]+)\]", flags=re.IGNORECASE)

def extract_citations(answer):
    return [x.strip() for x in SOURCE_PATTERN.findall(answer)]

def citation_diagnostics(result):
    cited = extract_citations(result["answer"])
    retrieved_ids = {x["chunk_id"] for x in result["sources"]}
    return {
        "citations": cited,
        "valid_citations": [x for x in cited if x in retrieved_ids],
        "invalid_citations": [x for x in cited if x not in retrieved_ids],
    }

print(json.dumps(citation_diagnostics(result), indent=2))

{
  "citations": [
    "resnet_2015_p001_c000",
    "resnet_2015_p002_c002",
    "resnet_2015_p001_c000"
  ],
  "valid_citations": [
    "resnet_2015_p001_c000",
    "resnet_2015_p002_c002",
    "resnet_2015_p001_c000"
  ],
  "invalid_citations": []
}

## 13. Inspect the exact evidence available to the generator

In [14]:
for rank, item in enumerate(result["retrieved_chunks"], 1):
    print("=" * 100)
    print(f"SOURCE #{rank}: {item['chunk_id']}")
    print(f"Paper: {item['title']} | Page: {item['page']} | Score: {item['score']:.4f}")
    print("-" * 100)
    print(item["text"])
    print()

====================================================================================================
SOURCE #1: resnet_2015_p001_c000
Paper: Deep Residual Learning for Image Recognition | Page: 1 | Score: 0.5869
----------------------------------------------------------------------------------------------------
Deep Residual Learning for Image Recognition Kaiming He Xiangyu Zhang Shaoqing Ren Jian Sun Microsoft Research {kahe, v-xiangz, v-shren, jiansun}@microsoft.com Abstract Deeper neural networks are more difﬁcult to train. We present a residual learning framework to ease the training of networks that are substantially deeper than those used previously. We explicitly reformulate the layers as learning residual functions with reference to the layer inputs, instead of learning unreferenced functions. We provide comprehensive empirical evidence showing that these residual networks are easier to optimize, and can gain accuracy from considerably increased depth. On the ImageNet dataset we evaluate residual nets with a depth of up to 152 layers—8× deeper than VGG nets [41] but still having lower complexity. An ensemble of these residual nets achieves 3.57% error on the ImageNet test set. This result won the 1st place on the ILSVRC 2015 classiﬁcation task

====================================================================================================
SOURCE #2: resnet_2015_p002_c008
Paper: Deep Residual Learning for Image Recognition | Page: 2 | Score: 0.5266
----------------------------------------------------------------------------------------------------
(approaching zero), the layers in highway networks represent non-residual functions. On the contrary, our formulation always learns residual functions our identity shortcuts are never closed, and all information is always passed through, with additional residual functions to be learned. In addition, high2

====================================================================================================
SOURCE #3: resnet_2015_p002_c002
Paper: Deep Residual Learning for Image Recognition | Page: 2 | Score: 0.5109
----------------------------------------------------------------------------------------------------
We show that: 1) Our extremely deep residual nets are easy to optimize, but the counterpart “plain” nets (that simply stack layers) exhibit higher training error when the depth increases; 2) Our deep residual nets can easily enjoy accuracy gains from greatly increased depth, producing results substantially better than previous networks. Similar phenomena are also shown on the CIFAR-10 set [20], suggesting that the optimization difﬁculties and the effects of our method are not just akin to a particular dataset. We present successfully trained models on this dataset with over 100 layers, and explore models with over 1000 layers. On the ImageNet classiﬁcation dataset [36], we obtain excellent results by extremely deep residual nets. Our 152layer residual net is the deepest network ever presented on ImageNet, while still having lower complexity than VGG nets [41]. Our ensemble has 3.57% top-5 error on the ImageNet test set, and won the 1st place in the ILSVRC 2015 classiﬁcation competition

====================================================================================================
SOURCE #4: resnet_2015_p002_c000
Paper: Deep Residual Learning for Image Recognition | Page: 2 | Score: 0.5065
----------------------------------------------------------------------------------------------------
identity weight layer weight layer relu relu F(x)+x x F(x) x Figure 2. Residual learning: a building block. are comparably good or better than the constructed solution (or unable to do so in feasible time). In this paper, we address the degradation problem by introducing a deep residual learning framework. Instead of hoping each few stacked layers directly ﬁt a desired underlying mapping, we explicitly let these layers ﬁt a residual mapping. Formally, denoting the desired underlying mapping as H(x), we let the stacked nonlinear layers ﬁt another mapping of F(x) := H(x)−x. The original mapping is recast into F(x)+x. We hypothesize that it is easier to optimize the residual mapping than to optimize the original, unreferenced mapping. To the extreme, if an identity mapping were optimal, it would be easier to push the residual to zero than to ﬁt an identity mapping by a stack of nonlinear layers

====================================================================================================
SOURCE #5: resnet_2015_p003_c000
Paper: Deep Residual Learning for Image Recognition | Page: 3 | Score: 0.5005
----------------------------------------------------------------------------------------------------
way networks have not demonstrated accuracy gains with extremely increased depth (e.g., over 100 layers). 3. Deep Residual Learning 3.1. Residual Learning Let us consider H(x) as an underlying mapping to be ﬁt by a few stacked layers (not necessarily the entire net), with x denoting the inputs to the ﬁrst of these layers. If one hypothesizes that multiple nonlinear layers can asymptotically approximate complicated functions2, then it is equivalent to hypothesize that they can asymptotically approximate the residual functions, i.e., H(x) −x (assuming that the input and output are of the same dimensions). So rather than expect stacked layers to approximate H(x), we explicitly let these layers approximate a residual function F(x) := H(x) −x. The original function thus becomes F(x)+x. Although both forms should be able to asymptotically approximate the desired functions (as hypothesized), the ease of learning might be different

## 14. Small baseline benchmark

This is a pipeline sanity-check benchmark, not the final research evaluation.

In [15]:
BASELINE_QUESTIONS = [
    {
        "id": "q01",
        "question": "What problem does residual learning address in very deep neural networks?",
        "expected_papers": ["resnet_2015"],
    },
    {
        "id": "q02",
        "question": "What is the main architectural idea of the Transformer?",
        "expected_papers": ["attention_2017"],
    },
    {
        "id": "q03",
        "question": "Why does the Transformer not require recurrence to model relationships between tokens?",
        "expected_papers": ["attention_2017"],
    },
    {
        "id": "q04",
        "question": "What is the purpose of pre-training in BERT?",
        "expected_papers": ["bert_2018"],
    },
    {
        "id": "q05",
        "question": "What are the two moment estimates used by Adam?",
        "expected_papers": ["adam_2014"],
    },
    {
        "id": "q06",
        "question": "How does Adam adapt the learning rate for individual parameters?",
        "expected_papers": ["adam_2014"],
    },
]
display(pd.DataFrame(BASELINE_QUESTIONS))

    id                                           question   expected_papers
0  q01  What problem does residual learning address in...     [resnet_2015]
1  q02  What is the main architectural idea of the Tra...  [attention_2017]
2  q03  Why does the Transformer not require recurrenc...  [attention_2017]
3  q04       What is the purpose of pre-training in BERT?       [bert_2018]
4  q05    What are the two moment estimates used by Adam?       [adam_2014]
5  q06  How does Adam adapt the learning rate for indi...       [adam_2014]

## 15. Run the benchmark

In [16]:
baseline_outputs = []

for item in tqdm(BASELINE_QUESTIONS, desc="Running baseline RAG"):
    output = baseline_rag(item["question"], top_k=5, max_new_tokens=300)
    diagnostics = citation_diagnostics(output)

    baseline_outputs.append({
        "question_id": item["id"],
        "question": item["question"],
        "expected_papers": item["expected_papers"],
        "answer": output["answer"],
        "sources": output["sources"],
        "retrieved_chunks": output["retrieved_chunks"],
        "retrieval_time_seconds": output["retrieval_time_seconds"],
        "generation_time_seconds": output["generation_time_seconds"],
        "prompt_tokens": output["prompt_tokens"],
        "generated_tokens": output["generated_tokens"],
        "citations": diagnostics["citations"],
        "valid_citations": diagnostics["valid_citations"],
        "invalid_citations": diagnostics["invalid_citations"],
    })

print("Completed:", len(baseline_outputs))

Running baseline RAG:   0%|          | 0/6 [00:00<?, ?it/s]

Completed: 6

## 16. Review generated answers

In [17]:
for record in baseline_outputs:
    print("=" * 110)
    print(f"{record['question_id']}: {record['question']}")
    print("-" * 110)
    print(record["answer"])
    print("\nCitations:", record["citations"])
    print("Invalid citations:", record["invalid_citations"])
    print()

==============================================================================================================
q01: What problem does residual learning address in very deep neural networks?
--------------------------------------------------------------------------------------------------------------
Residual learning addresses the problem of vanishing/exploding gradients in very deep neural networks, which hinders their convergence. As networks become deeper, residual learning helps prevent degradation in performance by allowing the network to learn residual functions that help maintain accuracy even as depth increases. This approach mitigates the issue of overfitting and allows for the training of very deep networks that achieve better performance than shallower networks. [SOURCE: resnet_2015_p001_c003]

Citations: ['resnet_2015_p001_c003']
Invalid citations: []

==============================================================================================================
q02: What is the main architectural idea of the Transformer?
--------------------------------------------------------------------------------------------------------------
The main architectural idea of the Transformer is the use of stacked self-attention mechanisms combined with point-wise, fully connected feed-forward networks. This architecture is illustrated in Figure 1 of the paper "Attention Is All You Need" [SOURCE: attention_2017_p003_c000].

Each layer consists of two sub-layers: a multi-head self-attention mechanism and a position-wise, fully connected feed-forward network. These sub-layers are connected using residual connections, followed by layer normalization. The Transformer model architecture is symmetric for both the encoder and decoder stacks, with each stack containing 6 identical layers.

Citations: ['attention_2017_p003_c000']
Invalid citations: []

==============================================================================================================
q03: Why does the Transformer not require recurrence to model relationships between tokens?
--------------------------------------------------------------------------------------------------------------
The Transformer does not require recurrence because it relies solely on self-attention to model relationships between tokens. This is evident from the text in [SOURCE: attention_2017_p002_c001] and [SOURCE: attention_2017_p002_c002], which states that the Transformer "allows for significantly more parallelization and can reach a new state of the art in translation quality after being trained for as little as twelve hours on eight P100 GPUs." Additionally, [SOURCE: attention_2017_p002_c005] mentions that "Attention mechanisms have become an integral part of compelling sequence modeling and transduction models in various tasks, allowing modeling of dependencies without regard to their distance in the input or output sequences." [SOURCE: bert_2018_p001_c004] further supports this by stating that "this limits the choice of architectures that can be used during pre-training," indicating that the Transformer avoids recurrence.

Citations: ['attention_2017_p002_c001', 'attention_2017_p002_c002', 'attention_2017_p002_c005', 'bert_2018_p001_c004']
Invalid citations: []

==============================================================================================================
q04: What is the purpose of pre-training in BERT?
--------------------------------------------------------------------------------------------------------------
The purpose of pre-training in BERT is to train the model on unlabeled data over different pre-training tasks. [SOURCE: bert_2018_p003_c002] During pre-training, BERT learns [SEP], [CLS] and sentence A/B embeddings, which are also learned during fine-tuning. [SOURCE: bert_2018_p014_c002] The pre-training tasks are illustrated with examples. [SOURCE: bert_2018_p012_c003] Pre-training helps the model understand language understanding tasks better. [SOURCE: bert_2018_p014_c001]

Citations: ['bert_2018_p003_c002', 'bert_2018_p014_c002', 'bert_2018_p012_c003', 'bert_2018_p014_c001']
Invalid citations: []

==============================================================================================================
q05: What are the two moment estimates used by Adam?
--------------------------------------------------------------------------------------------------------------
The two moment estimates used by Adam are the first moment (mean) and the second moment (variance).

[SOURCE: adam_2014_p003_c004] [SOURCE: adam_2014_p003_c003]

Citations: ['adam_2014_p003_c004', 'adam_2014_p003_c003']
Invalid citations: []

==============================================================================================================
q06: How does Adam adapt the learning rate for individual parameters?
--------------------------------------------------------------------------------------------------------------
Adam adapts the learning rate for individual parameters by scaling their gradients inversely proportional to a (scaled) L2 norm of their individual current and past gradients. Specifically, the update rule for individual weights is:

\[ \theta_{t+1} = \theta_t - \alpha \cdot \frac{g_t}{\sqrt{u_t + \epsilon}} \]

where:
- \( \alpha \) is the learning rate,
- \( g_t \) is the gradient of the loss function with respect to the parameters at time \( t \),
- \( u_t \) is the exponentially weighted infinity norm of the gradients,
- \( \epsilon \) is a small constant to avoid division by zero.

This approach helps in adapting the learning rate for each parameter individually, making it more efficient for training deep learning models. [SOURCE: adam_2014_p009_c000]

Citations: ['adam_2014_p009_c000']
Invalid citations: []

## 17. Basic baseline diagnostics

In [18]:
rows = []
for record in baseline_outputs:
    rows.append({
        "question_id": record["question_id"],
        "num_sources": len(record["sources"]),
        "num_citations": len(record["citations"]),
        "num_valid_citations": len(record["valid_citations"]),
        "num_invalid_citations": len(record["invalid_citations"]),
        "has_citation": bool(record["citations"]),
        "has_invalid_citation": bool(record["invalid_citations"]),
        "retrieval_time_seconds": record["retrieval_time_seconds"],
        "generation_time_seconds": record["generation_time_seconds"],
        "prompt_tokens": record["prompt_tokens"],
        "generated_tokens": record["generated_tokens"],
    })

baseline_metrics_df = pd.DataFrame(rows)
display(baseline_metrics_df)

print("Citation presence:",
      round(baseline_metrics_df["has_citation"].mean() * 100, 2), "%")
print("Invalid citation rate:",
      round(baseline_metrics_df["has_invalid_citation"].mean() * 100, 2), "%")
print("Mean retrieval time:",
      round(baseline_metrics_df["retrieval_time_seconds"].mean(), 3), "s")
print("Mean generation time:",
      round(baseline_metrics_df["generation_time_seconds"].mean(), 3), "s")

,question_id,num_sources,num_citations,num_valid_citations,num_invalid_citations,has_citation,has_invalid_citation,retrieval_time_seconds,generation_time_seconds,prompt_tokens,generated_tokens
0,q01,5,1,1,0,True,False,0.017638,7.328718,1136,102
1,q02,5,1,1,0,True,False,0.010467,9.758369,1005,129
2,q03,5,4,4,0,True,False,0.014494,15.271464,1029,210
3,q04,5,4,4,0,True,False,0.010353,10.809471,1075,144
4,q05,5,2,2,0,True,False,0.010304,5.041092,1147,59
5,q06,5,1,1,0,True,False,0.012491,14.108763,1294,187

Citation presence: 100.0 %
Invalid citation rate: 0.0 %
Mean retrieval time: 0.013 s
Mean generation time: 10.386 s

## 18. Expected-paper retrieval hit rate

In [19]:
def retrieval_paper_hit(record):
    retrieved_papers = {s["paper_id"] for s in record["sources"]}
    return bool(retrieved_papers.intersection(record["expected_papers"]))

coverage = pd.DataFrame([
    {
        "question_id": r["question_id"],
        "expected_papers": r["expected_papers"],
        "retrieval_hit": retrieval_paper_hit(r)
    }
    for r in baseline_outputs
])

display(coverage)
print(
    "Expected-paper retrieval hit rate:",
    round(coverage["retrieval_hit"].mean() * 100, 2), "%"
)

  question_id   expected_papers  retrieval_hit
0         q01     [resnet_2015]           True
1         q02  [attention_2017]           True
2         q03  [attention_2017]           True
3         q04       [bert_2018]           True
4         q05       [adam_2014]           True
5         q06       [adam_2014]           True

Expected-paper retrieval hit rate: 100.0 %

## 19. Save the baseline experiment

In [20]:
experiment_name = "baseline_rag_v1"

metadata = {
    "experiment": experiment_name,
    "model": MODEL_NAME,
    "embedding_model": EMBEDDING_MODEL_NAME,
    "top_k": 5,
    "max_new_tokens": 300,
    "sampling": False,
    "temperature": 0.0,
    "corpus_metadata": corpus_metadata,
    "num_questions": len(baseline_outputs),
    "runtime": (
        torch.cuda.get_device_name(0)
        if torch.cuda.is_available() else "CPU"
    ),
}

payload = {"metadata": metadata, "results": baseline_outputs}

json_path = RESULTS_DIR / f"{experiment_name}.json"
csv_path = RESULTS_DIR / f"{experiment_name}_metrics.csv"

with json_path.open("w", encoding="utf-8") as f:
    json.dump(payload, f, indent=2, ensure_ascii=False)

baseline_metrics_df.to_csv(csv_path, index=False)

print("Saved:", json_path)
print("Saved:", csv_path)

Saved: /content/Verified-RAG/results/baseline_rag_v1.json
Saved: /content/Verified-RAG/results/baseline_rag_v1_metrics.csv

# Baseline RAG complete

We now have:

```text
Question
   ↓
MiniLM embedding
   ↓
FAISS
   ↓
Top-k evidence
   ↓
Qwen2.5-3B-Instruct
   ↓
Cited answer
```

The baseline does **not** independently verify whether claims are supported. It does not perform claim decomposition, evidence checking, contradiction detection, or regeneration.

Those capabilities will be introduced in `03_multi_agent_rag.ipynb`.

The saved baseline results become the **control condition** for the research experiments.

In [ ]:
import json
from pathlib import Path
from google.colab import _message

# 1. Download current notebook JSON into the repo's notebooks/ folder
notebook_json = _message.blocking_request("get_ipynb")
target_nb_path = Path("/content/Verified-RAG/notebooks/02_baseline_rag.ipynb")

with open(target_nb_path, "w", encoding="utf-8") as f:
    json.dump(notebook_json["ipynb"], f, indent=2)

print(f"Saved notebook to {target_nb_path}")